apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agentgateway.yaml
  - agentregistry.yaml
  - agent-graph-rag.yaml
  - kagent.yaml
  - llama-cpp-embeddings.yaml
  - llmd.yaml
  - mcp-servers.yaml
  - modelconfig-gemini.yaml
  - neo4j.yaml
  - phoenix.yaml
  - qdrant.yaml
